
(library
  (name ttag)
  (modules ttag)
  (preprocess (pps
    ppx_sexp_conv
    ppx_enumerate
    ppx_deriving.eq
  ))
)

(library
  (name metadata)
  (modules metadata)
  (libraries
    sexplib
    ttag)
  (preprocess (pps ppx_sexp_conv))
)

(executable
 (name feat_count)
 (modules feat_count)
 (libraries ttag latex_tbl metadata utils))