(rule
 (action
  (bash
   "python3 uncombine.py --prefix combined --ignore-combined uncombine.py --combined %{deps} --targets %{targets}"))
 (deps uncombine.py combinedLexerDesc.mll combinedParserDesc.mly)
 (targets
  bluejayLexerDesc.mll
  bluejayParserDesc.mly
  desugaredLexerDesc.mll
  desugaredParserDesc.mly
  embeddedLexerDesc.mll
  embeddedParserDesc.mly))

(ocamllex bluejayLexerDesc desugaredLexerDesc embeddedLexerDesc)

(menhir
 (modules bluejayParserDesc desugaredParserDesc embeddedParserDesc))

(library
 (name lang)
 (public_name jay.lang)
 (synopsis "Languages in Jaylang")
 (modules (:standard))
 (libraries baby cmdliner utils)
 (preprocess
  (pps ppx_deriving.eq ppx_deriving.ord jay_ppx_local)))
