(include_subdirs qualified)

(library
 (name concolic)
 (public_name jay.concolic)
 (libraries
  translate
  interpreter
  cmdliner
  interp_common
  baby
  psq
  mtime
  nel
 )
 (synopsis "Concolic evaluator on embedded-type programs")
 (inline_tests)
 (instrumentation (backend landmarks --auto)) ; use `dune build --instrument-with landmarks` to get instrumentation
 (preprocess
  (pps
   ppx_deriving.eq
   jay_ppx_local)))